---
- name: Updates and Install Packages
  hosts: all
  gather_facts: yes
  tasks:
    - name: Update and Install Packages
      block:
      when: ansible_pkg_mgr == "yum"
      - name: Update Packages
        yum:
          name: '*'
          state: latest
      - name: Install Packages
        yum:
          name: ["git", "tree", "curl", "wget"]